# Generated by Django 2.1.3 on 2018-11-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20181108_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.TextField(default='test summary text', help_text='Enter a brief description of the book', max_length=1000),
            preserve_default=False,
        ),
    ]
